### ISSUE TITLE
Think of maybe using a linter...?

### ISSUE THREAD

**Issue by Mortuie** [chingu-voyage3/bears-21#10]

**Comment by nikrb** [comment]
create-react-app setup up 'react-app' linting rules by default. You'll see errors/warnings in the console on 'compile'. For atom, include .eslintrc in root dir with :
```
{
  "extends": "react-app"
}
```

**Comment by Mortuie** [comment]
I think create-react-app uses: 
Dependencies
Like Babel, ESLint, and Webpack.

ESLint by default which is a popular js linter.

**Comment by nikrb** [comment]
having trouble with state def and arrow function syntax in classes with current linting. looks like babel-eslint parser is the answer.

**Comment by vivekimsit** [comment]
@nikrb I think react has their preset
