### ISSUE TITLE
Getting front and backend to run off the same npm start command

### ISSUE THREAD

**Issue by Mortuie** [chingu-voyage3/bears-21#11]
Ideally we want all the code running on one server to make deployment/integration and maintaining much easier...

**Comment by nikrb** [comment]
take a look at this, [Fullstack React](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/)
I used this setup for my fcc fullstack (backend) projects. I have a [template](https://github.com/nikrb/auth_react-base) (including passport local auth) if this helps. It's simple, but we can always complicate it as we proceed :)

**Comment by Mortuie** [comment]
I was thinking of something like this: 
You can upload this folder to a host like S3 and deploy your app to AWS. Or, you can have the API server also serve your static assets.

Essentially we would be pushing the /build folder generated by npm run build of our react codebase. So that it is essentially static. Then the node server serves our files by pointing to that position. But i'm open to suggestions.
