### ISSUE TITLE
run time server deprecation warnings

### ISSUE THREAD

**Issue by nikrb** [chingu-voyage3/bears-21#40]
some warning for express session init:
```
express-session deprecated undefined resave option; provide resave option web/app.js:42:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option web/app.js:42:9
```

**Comment by Mortuie** [comment]
There is also a MONGODB deprecation warning ?

**Comment by nikrb** [comment]
the useMongoCient warning? That seems to have been addressed, atleast I don't see it locally.

**Comment by nikrb** [comment]
still getting the useMongoClient warning. @vivekimsit have we lost your fix?

**Comment by nikrb** [comment]
useMongoClient removed in another pr so closing
