### ISSUE TITLE
Getting React Router working for our basic pages.

### ISSUE THREAD

**Issue by Mortuie** [chingu-voyage3/bears-21#5]

**Comment by nikrb** [comment]
I used react-router-dom (react router V4) in my fcc fullstack projects, [here](https://github.com/nikrb/fcc-vote/blob/master/client/src/App.js) is an example.

**Comment by Mortuie** [comment]
I have looked at exactly that project to try and learn React Router v4 a little better. I must say I'm starting to like it a lot. Also been really helpful. So when I push my code I need a code review from @nikrb ;)
