### ISSUE TITLE
Test framework in a JS library especially for the backend.

### ISSUE THREAD

**Issue by Mortuie** [chingu-voyage3/bears-21#8]
I think having a couple of tests won't really hurt anyone.

**Comment by nikrb** [comment]
create-react-app comes with Jest by default. I have some simple tests in my fcc rogue-like [dungeon crawler](https://github.com/nikrb/fcc_rogue-game/tree/master/src/components/Game) example app.

**Comment by Mortuie** [comment]
Open to discussion we can use any framework. I've only touched mocha for some stuff on the backend. I'm more worried about the front-end rather than the backend. But we can do both. Again I don't really mind. This is more for later, if we decide to integrate Travis CI & such like to help us. But again no idea and open to suggestion.
