### ISSUE TITLE
Setup Heroku & CI when we have a substantial part of the project going..

### ISSUE THREAD

**Issue by Mortuie** [chingu-voyage3/bears-21#9]

**Comment by nikrb** [comment]
heroku setup is described in create-react-app dox/deployment. After creating heroku app, put the following in package.json scripts and it builds after `git push heroku master`:
```
    "start": "node server",
    "heroku-postbuild": "cd client/ && npm install && npm install --only=dev --no-shrinkwrap && npm run build"
```

**Comment by Mortuie** [comment]
Oo juicy, but I've done heroku deploys using the microservices which I find really nice. So if we get our project running off one single command it would be quite easy to do. Again only my thoughts.
